opencv:
  #methods: ["CLAHE", "EQUALIZE_HIST", "EQUALIZE_HIST_YUV", "HSV", ...
  # "INVERT", "GRAYSCALE", "THRESHOLD", "DILATION", "EROSION", "CANNY", "THINNING","RANGE"]
  methods: ["GRAYSCALE", "INVERT", "DILATION", "CANNY", "THINNING"]
  debug_mode_enable: true
  debug_window_name: "DEBUG_REGION_DETECTION"
  debug_wait_key: false
  hsv:
    h: [0, 180]
    s: [100, 255]
    v: [0, 80]
  threshold:
   type: 0
   value: 180
  canny:
   lower_threshold: 50
   upper_threshold: 210
   aperture_size: 1
  dilation:
   elem: 1 # 0: Rect, 1: Cross, 2: Ellipse
   kernel_size: 1 # 2n + 1
  erosion:
   elem: 1 # 0: Rect, 1: Cross, 2: Ellipse
   kernel_size: 1 # 2n + 1
  contour:
   method: 1
   mode: 1 # See cv::RetrievalModes
  range:
    low: 190
    high: 255
  clahe:
    clip_limit: 4.0
    tile_grid_size: [4, 4]
pcl2d:
  downsampling_radius: 4.0 #  pixel units
  split_dist: 6.0 #  pixel units
  closed_curve_max_dist: 6.0 #  pixel units
  simplification_min_points: 10 #  applies simplification only if the closed curve has 10 points or more
  simplification_alpha: 24.0 #  pixel units, used in concave hull step   
pcl:
  debug_mode_enable: false
  max_merge_dist: 0.03
  closed_curve_max_dist: 0.03
  simplification_min_dist: 0.01
  split_dist: 0.1
  min_num_points: 10
  stat_removal:
   enable: true
   kmeans: 100
   stddev: 3.0
  normal_est:
   downsampling_radius: 0.01
   search_radius: 0.02
   kdtree_epsilon: 0.001
   viewpoint_xyz: [0.0, 0.0, 100.0]

