crs:
  general: {}
  motion_planning:
    pre_move_home: false
    home_position:
      joint_names: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]
      joint_position: [-0.9644, -1.3617, 2.0724, -0.7108, -0.9640, 0.7994]
    process_path:
      tool_speed: 0.1
      offset_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # [px, py, pz, rx, ry, rz] relative to default tool
      retreat_dist: 0.03
      approach_dist: 0.03
      tool_frame: "sander_center_link"
      target_force: 50
    media_change:
      change_time: 300.0 # seconds
      joint_names: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]
      joint_position: [-0.02467, -1.7719, -1.8680, -0.6212, 0.90265, -2.2430]
    preview:
      time_scaling: 1.0
  scan_acquisition: 
    scan_poses:
      - pose: [-0.869, -0.397, 1.559, -3.1289652, 0.6427091, 3.1099935]
      - pose: [0.005, 0.621, 1.534, -2.6741055, -0.6119461, -1.9862345]
      - pose: [-0.348, -0.211, 1.555, -2.2509677, -0.1362007, -3.0876068]
      - pose: [0.036, 0.258, 1.549, -2.4653191, -0.7150566, 2.9155958]
      - pose: [-0.201, -0.062, 1.604, 2.4117773, -0.3157807, -2.7579127]
      - pose: [0.016, 0.604, 1.700, 2.5848052, -0.6232238, 3.0450751]
    tool_frame: "camera_link_optical" 
    skip_on_failure: true
  process_execution:
    time_tolerance: 5.0 # seconds
    joint_tolerance: [0.035, 0.035, 0.035, 0.035, 0.035, 0.035] # radians
    cartesian_path_tolerance: [0.015, 0.015, 0.025, 0.15, 0.15, 0.15]
    cartesian_goal_tolerance: [0.01, 0.01, 0.01, 0.05, 0.05, 0.05]
    force_tolerance: 5
    force_controlled_trajectories: true
    ur_tool_change_script: 'simpleMove.urp'
    execute_tool_change: false
  part_registration:
    simulation_pose: [-0.7, 0.0, 1.1, 0.0, 0.0, 0.0]  # used for simulator only
    seed_pose: [0.0, 0.0, 0.5, 0.0, 0.0, 0.0]
    target_frame_id: "world"
    part_file: "null"      # relative to known data directory
    toolpath_file: "null"  # relative to known data directory
  part_rework: 
    scan_poses:
      - pose: [-0.869, -0.397, 1.559, -3.1289652, 0.6427091, 3.1099935]
      - pose: [0.005, 0.621, 1.534, -2.6741055, -0.6119461, -1.9862345]
      - pose: [-0.348, -0.211, 1.555, -2.2509677, -0.1362007, -3.0876068]
      - pose: [0.036, 0.258, 1.549, -2.4653191, -0.7150566, 2.9155958]
      - pose: [-0.201, -0.062, 1.604, 2.4117773, -0.3157807, -2.7579127]
      - pose: [0.016, 0.604, 1.700, 2.5848052, -0.6232238, 3.0450751]
    tool_frame: "camera_link_optical" 
    pre_acquisition_pause: 2.0 # seconds
    skip_on_failure: true
