general:
  mesh_num_samples: 100000
  leaf_size: 0.02
  part_frame: "part"
  enable_debug_visualizations: True
icp:
  max_correspondence_dist: 0.3
  max_iter: 1500
  transformation_eps: 1e-12
  rotation_eps: 1e-12  # transformation rotation epsilon in order for an optimization to be considered as having converged to the final solution (epsilon is the cos(angle)
  euclidean_fitness: 1e-12
  ransac_threshold: 0.05
  use_correspondences: True
  use_cog_alignment: False
sac:
  normal_est_rad: 0.1
  feature_est_rad: 0.04
  max_iters: 10000
  num_samples: 3
  correspondence_rand: 5
  similarity_threshold: 0.1
  max_correspondence_dist: 0.02
  inlier_fraction: 0.25
crop_boxes:
  box1:
    xyz: [-0.4, 0.0, 1.15]
    size: [2.0, 2.0, 0.8]
    reverse: True
  box2:
    xyz: [-0.4, 0.0, 0.56]
    size: [0.7, 3.0, 0.8]
    reverse: False # deletes what's inside the box
  box3:
    xyz: [0.25, -0.8, 1.3]
    size: [0.5, 0.5, 0.5]
    reverse: False # deletes what's inside the box
